[2023-06-30T05:09:21.546+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BigData_Pipeline.store_metadata_in_cloud_sql_task manual__2023-06-30T05:08:47.731055+00:00 [queued]>
[2023-06-30T05:09:21.553+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BigData_Pipeline.store_metadata_in_cloud_sql_task manual__2023-06-30T05:08:47.731055+00:00 [queued]>
[2023-06-30T05:09:21.553+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-30T05:09:21.563+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): store_metadata_in_cloud_sql_task> on 2023-06-30 05:08:47.731055+00:00
[2023-06-30T05:09:21.568+0000] {standard_task_runner.py:57} INFO - Started process 274 to run task
[2023-06-30T05:09:21.572+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'BigData_Pipeline', 'store_metadata_in_cloud_sql_task', 'manual__2023-06-30T05:08:47.731055+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp01j38rzw']
[2023-06-30T05:09:21.573+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask store_metadata_in_cloud_sql_task
[2023-06-30T05:09:21.587+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-06-30T05:09:21.617+0000] {task_command.py:410} INFO - Running <TaskInstance: BigData_Pipeline.store_metadata_in_cloud_sql_task manual__2023-06-30T05:08:47.731055+00:00 [running]> on host c32bbac66861
[2023-06-30T05:09:21.695+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BigData_Pipeline' AIRFLOW_CTX_TASK_ID='store_metadata_in_cloud_sql_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T05:08:47.731055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-30T05:08:47.731055+00:00'
[2023-06-30T05:09:22.548+0000] {logging_mixin.py:149} INFO - Getting data from XCom...
[2023-06-30T05:09:22.561+0000] {logging_mixin.py:149} INFO - date: 20150721
[2023-06-30T05:09:22.562+0000] {logging_mixin.py:149} INFO - Storing metadata in Cloud SQL...
[2023-06-30T05:09:22.658+0000] {logging_mixin.py:149} INFO - Connecting to Cloud SQL...
[2023-06-30T05:09:22.658+0000] {logging_mixin.py:149} INFO - pool: <sqlalchemy.engine.base.Connection object at 0xffff91973810>
[2023-06-30T05:09:28.200+0000] {logging_mixin.py:149} INFO - Metadata loaded to Cloud SQL
[2023-06-30T05:09:28.209+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-30T05:09:28.243+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=BigData_Pipeline, task_id=store_metadata_in_cloud_sql_task, execution_date=20230630T050847, start_date=20230630T050921, end_date=20230630T050928
[2023-06-30T05:09:28.363+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-30T05:09:28.385+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
